/**
 * fleet/tests/_readiness_helpers.mjs — the fold-order sim's machinery.
 *
 * Underscore-prefixed so test_fleet_suite.py's `test_*.mjs` glob does not run
 * it as a test of its own; `fleet/tests/test_readiness_fold_order.mjs` is the
 * sim, and `fleet/tests/test_readiness_fold_order_exam.mjs` the exam that
 * grades it.
 *
 * The one export the plan pins is `runSet(spec)`. Everything else here exists
 * to build a `spec`: the fixture corpus, the committed reply roots, the
 * real-join sets under `fleet/tests/fixtures/readiness/`.
 *
 * What a set is
 * -------------
 * A set is a BASE commit in a scratch repo plus N task patches taken against
 * it (`git diff --binary --full-index --no-renames <BASE>`, exactly what
 * `corpuslib._capture_patch` writes). `runSet` folds it twice over:
 *
 *   simultaneously  one `fold` over all N patches, one `materialize`;
 *   sequentially    for every order the kernel's own `sampled_orders(N)`
 *                   returns, one step per task — `adopted` (the diff from
 *                   BASE to the head built so far) alongside the next task's
 *                   patch, folded against BASE and materialized onto that
 *                   head.
 *
 * and returns both answers. The claim under measurement is that every order's
 * candidate `^{tree}` equals the simultaneous candidate's.
 *
 * Three facts about the kernel this file is built around, each paid for by
 * hand before it was written:
 *
 *   - `fold` exits 2 when `<run-dir>/frontier/wave-<n>/fold_log.jsonl` already
 *     exists, so every step gets a run directory of its own.
 *   - a set's `commutes` declaration has to be carried onto the `adopted`
 *     pseudo-task at every step where an already-adopted task declared that
 *     path. Corpus wave 2 (two appends at one anchor, both declared
 *     commutative) narrates a `lines` conflict on `c.txt` at its second step
 *     and falls back in `materialize` without it.
 *   - `resolve` takes no `--base`; it reads the base out of the fold log.
 *
 * Replies are never generated by the sim. A conflict's reply is a committed
 * file under a reply root laid out the way a real-join fixture lays it out —
 * `<root>/<path, "/" as "__">/h<N>.txt` — and `runSet` copies the bytes of
 * exactly the hunk files one conflict names into the dir it hands `resolve`.
 * A reply is keyed by `(set, path, hunk id)` and never by which side the
 * narration happened to label `frontier`: wave 3's conflict shows `3b` on the
 * right simultaneously and on the left in the order that adopts it first, and
 * the resolved region is one file either way.
 *
 * `spec.replies` also accepts a function, for a caller that wants to build a
 * divergence rather than commit one: it is called per hunk with
 * `{path, hunk, mode, order, step}` and returns that hunk's reply text. The sim
 * itself never passes one — every set it runs answers from a committed root, so
 * the constraint that no reply is produced at test time holds where it is
 * claimed. The form exists because the negative control IS a set whose reply is
 * not a function of `(set, path, hunk)` alone, and an examiner building its own
 * control should not have to commit two texts to do it.
 *
 * Soft edges: a task may carry a `base` of its own — the head it was
 * re-captured against, rather than the set's BASE. Tasks are grouped into
 * layers by that recorded base (the set's own BASE first, then each soft base
 * in the order it first appears), and a layer folds against its own base and
 * materializes onto the head the layer before it built. A recorded base already
 * carries the work it was taken over, so a soft-edge step folds its task alone,
 * with no `adopted` pseudo-task beside it. Sequentially, a sampled order is
 * stabilized to respect that layering — a soft edge slides to just after the
 * last task of every earlier layer — which reorders an order, never drops one.
 */

import { createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { simEnv } from './_helpers.mjs'

const HERE = path.dirname(fileURLToPath(import.meta.url))

/** The checkout this sim measures — `fleet/tests/../..`. */
export const REPO_ROOT = path.resolve(HERE, '..', '..')
export const KERNEL_DIR = path.join(REPO_ROOT, 'skills', 'ultrapowers', 'kernel')
export const FOLD_WAVE = path.join(KERNEL_DIR, 'fold_wave.py')
export const FRONTIER_DIR = path.join(REPO_ROOT, 'evals', 'frontier')

/** The default root M6 scans; `READINESS_FIXTURES_DIR` overrides it. */
export const FIXTURES_ROOT = path.join(HERE, 'fixtures', 'readiness')

/**
 * The committed replies. `corpus/` answers corpus wave 3's one `lines`
 * conflict on `d.txt`; `control/step-<n>/` are the negative control's, one per
 * step index the conflict can arise at — that is the whole trick of the
 * control, and the reason its orders diverge.
 */
export const REPLIES_ROOT = path.join(HERE, 'fixtures', 'readiness-corpus', 'replies')
export const CORPUS_REPLIES = path.join(REPLIES_ROOT, 'corpus')
export const CONTROL_REPLIES = path.join(REPLIES_ROOT, 'control')

/** The pseudo-task carrying everything adopted so far into a sequential step. */
export const ADOPTED = 'adopted'

/**
 * One environment for every child this module starts — `simEnv` plus a fixed
 * git identity and clock, so a scratch repo built here has the same sha on
 * every box. `os.devNull` rather than a literal: the hermetic probe's absolute
 * path rule, and a developer's `~/.gitconfig` has no business here anyway.
 */
const ENV = {
  ...simEnv(),
  GIT_AUTHOR_NAME: 'readiness fold sim',
  GIT_AUTHOR_EMAIL: 'readiness@example.invalid',
  GIT_COMMITTER_NAME: 'readiness fold sim',
  GIT_COMMITTER_EMAIL: 'readiness@example.invalid',
  GIT_AUTHOR_DATE: '2026-09-13T00:00:00+00:00',
  GIT_COMMITTER_DATE: '2026-09-13T00:00:00+00:00',
  GIT_CONFIG_GLOBAL: os.devNull,
  GIT_CONFIG_SYSTEM: os.devNull,
  TZ: 'UTC',
}

/** The environment, for a caller that spawns the sim itself. */
export const simRunEnv = () => ({ ...ENV })

// ── process plumbing ──────────────────────────────────────────────────────

/**
 * Run `file argv`, returning `{ status, stdout, stderr }`. Never throws on a
 * non-zero exit: the kernel says 0 at a stop, 2 at a refusal and 3 at a
 * fallback, and every one of those carries a reply on stdout the caller reads.
 */
export function sh (file, argv, { cwd = REPO_ROOT, buffer = false } = {}) {
  try {
    const stdout = execFileSync(file, argv, {
      cwd, env: ENV, encoding: buffer ? 'buffer' : 'utf8',
      maxBuffer: 64 * 1024 * 1024, stdio: ['ignore', 'pipe', 'pipe'],
    })
    return { status: 0, stdout, stderr: buffer ? Buffer.alloc(0) : '' }
  } catch (e) {
    if (e.status === undefined) throw e
    return { status: e.status, stdout: e.stdout, stderr: e.stderr }
  }
}

/** `git -C cwd argv…`, trimmed; throws with git's own stderr on failure. */
export function git (argv, cwd) {
  const r = sh('git', ['-C', cwd, ...argv])
  if (r.status !== 0) {
    throw new Error('git ' + argv.join(' ') + ' in ' + cwd + ' failed: ' + String(r.stderr || ''))
  }
  return String(r.stdout).trim()
}

/** `git -C cwd argv…` with binary stdout kept as bytes. */
function gitBytes (argv, cwd) {
  const r = sh('git', ['-C', cwd, ...argv], { buffer: true })
  if (r.status !== 0) {
    throw new Error('git ' + argv.join(' ') + ' in ' + cwd + ' failed: ' + String(r.stderr || ''))
  }
  return r.stdout
}

/** The `^{tree}` sha of a commit — the thing every assertion here compares. */
export const treeOf = (repo, sha) => git(['rev-parse', sha + '^{tree}'], repo)

/** `python3 -c <src> args…`; throws with the interpreter's stderr. */
function py (src, args = []) {
  const r = sh('python3', ['-c', src, ...args])
  if (r.status !== 0) {
    throw new Error('python3 -c failed (' + r.status + '): ' + String(r.stderr || ''))
  }
  return String(r.stdout)
}

export const sha256OfBytes = (bytes) => createHash('sha256').update(bytes).digest('hex')
export const sha256OfFile = (file) => sha256OfBytes(fs.readFileSync(file))

/** A fresh scratch directory under the temp root the sim was handed. */
export const mkTemp = (prefix) => fs.mkdtempSync(path.join(os.tmpdir(), prefix))

// ── the kernel's own order sampler ────────────────────────────────────────

const ORDERS_SRC = [
  'import sys, json',
  'sys.path.insert(0, sys.argv[1])',
  'from frontier_fold import sampled_orders',
  'print(json.dumps(sampled_orders(int(sys.argv[2]))))',
].join('\n')

const orderCache = new Map()

/**
 * `sampled_orders(n)` read out of the kernel rather than reimplemented — all
 * n! for n <= 4, the identity plus 19 seeded shuffles above. The sim may never
 * sample fewer orders than this returns.
 */
export function sampledOrders (n) {
  if (!orderCache.has(n)) orderCache.set(n, JSON.parse(py(ORDERS_SRC, [KERNEL_DIR, String(n)])))
  return orderCache.get(n).map((o) => o.slice())
}

// ── the fixture corpus ────────────────────────────────────────────────────

const CORPUS_SRC = [
  'import sys, json',
  'sys.path.insert(0, sys.argv[1])',
  'import corpuslib',
  'repo, corpus = corpuslib.make_fixture_corpus(sys.argv[2])',
  'print(json.dumps({"repo": str(repo), "corpus": str(corpus),',
  '                  "waves": sorted(corpuslib.SCENARIOS),',
  '                  "tasks": {str(w): sorted(t) for w, t in corpuslib.SCENARIOS.items()},',
  '                  "commutes": {str(w): c for w, c in corpuslib.FIXTURE_COMMUTES.items()}}))',
].join('\n')

/**
 * Build the synthetic corpus under `dest` with the real `corpuslib`, and
 * return what a spec needs from it: the scratch repo, its BASE, the per-wave
 * task ids and commutes, and where each task's patch landed.
 */
export function buildCorpus (dest) {
  fs.mkdirSync(dest, { recursive: true })
  const info = JSON.parse(py(CORPUS_SRC, [FRONTIER_DIR, dest]))
  const repo = info.repo
  const base = git(['rev-parse', 'HEAD'], repo)
  const patchesDir = path.join(dest, 'work', 'patches')
  return {
    dest,
    repo,
    base,
    waves: info.waves,
    tasksOf: (wave) => info.tasks[String(wave)].slice(),
    commutesOf: (wave) => JSON.parse(JSON.stringify(info.commutes[String(wave)] ?? {})),
    patchOf: (wave, id) => path.join(patchesDir, 'wave-' + wave, 'task-' + id + '.patch'),
  }
}

/** A corpus wave as a `runSet` spec. */
export function corpusWaveSpec (corpus, wave, { replies = CORPUS_REPLIES, workDir } = {}) {
  return {
    name: 'wave-' + wave,
    repo: corpus.repo,
    base: corpus.base,
    wave,
    tasks: corpus.tasksOf(wave).map((id) => ({ id, patch: corpus.patchOf(wave, id) })),
    commutes: corpus.commutesOf(wave),
    replies,
    workDir,
  }
}

// ── reply roots ───────────────────────────────────────────────────────────

/** A reply root's directory for one repo path: `/` spelled `__`. */
export const replyDirFor = (root, filePath) => path.join(root, filePath.split('/').join('__'))

/** The committed file answering hunk `hunkId` of a conflict on `filePath`. */
export const replyFileFor = (root, filePath, hunkId) => path.join(replyDirFor(root, filePath), hunkId + '.txt')

/** The hunk ids a conflict's hunks file briefs a resolver on, in order. */
export function hunkIdsOf (hunksFile) {
  return fs.readFileSync(hunksFile, 'utf8').split('\n')
    .filter((line) => line.startsWith('HUNK '))
    .map((line) => line.split(' ')[1])
}

/**
 * The one way a set answers a hunk: `(ctx) => Buffer`, `ctx` being
 * `{path, hunk, mode, order, step}`.
 *
 * Three spellings, in the order they are consulted:
 *
 *   `spec.replies` a function   the caller's own text, produced per hunk
 *   `spec.replyRootAt`          a committed reply root chosen per hunk-call —
 *                               the negative control, whose whole trick is
 *                               that the root it picks is not a function of
 *                               `(set, path, hunk)`
 *   `spec.replies` a path       one committed root for the whole set
 *
 * A committed file's bytes are read and never rewritten, so the `sha256` in
 * `repliesUsed` is the sha256 of the file on disk.
 */
function replyResolverFor (spec) {
  if (typeof spec.replies === 'function') {
    return (ctx) => {
      const text = spec.replies(ctx)
      if (typeof text !== 'string') {
        throw new Error('the reply function for (' + ctx.path + ', ' + ctx.hunk
          + ') returned ' + typeof text + ', not the hunk\'s reply text')
      }
      return Buffer.from(text, 'utf8')
    }
  }
  const rootAt = spec.replyRootAt ?? (() => spec.replies ?? null)
  return (ctx) => {
    const root = rootAt(ctx)
    const file = root ? replyFileFor(root, ctx.path, ctx.hunk) : null
    if (!file || !fs.existsSync(file)) {
      throw new Error('no committed reply for (' + ctx.path + ', ' + ctx.hunk + ') under ' + root)
    }
    return fs.readFileSync(file)
  }
}

// ── one fold, simultaneous or one sequential step ─────────────────────────

const waveDirOf = (runDir, wave) => path.join(runDir, 'frontier', 'wave-' + wave)

/** The `(path, kind)` pairs a wave directory narrated, deduped and sorted. */
function conflictKeysOf (waveDir) {
  const index = path.join(waveDir, 'conflicts.json')
  if (!fs.existsSync(index)) return []
  return dedupeKeys(JSON.parse(fs.readFileSync(index, 'utf8')).map((e) => [e.path, e.kind]))
}

function dedupeKeys (keys) {
  const seen = new Map()
  for (const [p, kind] of keys) seen.set(p + '\x00' + kind, [p, kind])
  return [...seen.keys()].sort().map((k) => seen.get(k))
}

function dedupeReplies (entries) {
  const seen = new Map()
  for (const e of entries) seen.set(e.path + '\x00' + e.hunk + '\x00' + e.sha256, e)
  return [...seen.keys()].sort().map((k) => seen.get(k))
}

/**
 * Fold `tasks` against `base` in a run directory of their own, answer every
 * conflict the kernel opens from `replyRoot`, and materialize onto `prevHead`.
 *
 * Returns the candidate sha, the narrated `(path, kind)` pairs, the committed
 * replies spent, and the number of kernel CLI calls it cost.
 */
function foldOnce ({ repo, base, wave, tasks, commutes, runDir, prevHead, replyFor, scratch }) {
  const patchArgs = tasks.flatMap((t) => ['--patch', t.id + '=' + t.patch])
  const commuteArgs = Object.keys(commutes ?? {}).sort()
    .flatMap((id) => ['--commutes', id + '=' + commutes[id].join(',')])
  const common = ['--repo', repo, '--run-dir', runDir, '--wave', String(wave)]

  let calls = 0
  const kernel = (argv) => {
    calls += 1
    const r = sh('python3', [FOLD_WAVE, ...argv])
    const out = String(r.stdout || '').trim()
    if (!out.startsWith('{')) {
      throw new Error('kernel ' + argv[0] + ' said nothing readable (exit ' + r.status + '): '
        + out + String(r.stderr || ''))
    }
    return JSON.parse(out)
  }

  let reply = kernel(['fold', ...common, '--base', base, ...patchArgs, ...commuteArgs])

  const repliesUsed = []
  let pending = reply.open ?? []
  let guard = 0
  while (!reply.complete) {
    if (!pending.length) {
      throw new Error('fold left nothing dispatchable and did not complete: ' + JSON.stringify(reply))
    }
    if (++guard > 64) throw new Error('resolve loop did not converge')
    const entry = pending.shift()
    const dir = fs.mkdtempSync(path.join(scratch, 'reply-'))
    for (const hunk of hunkIdsOf(entry.hunksFile)) {
      const bytes = replyFor({ path: entry.path, hunk })
      fs.writeFileSync(path.join(dir, hunk + '.txt'), bytes)
      repliesUsed.push({ path: entry.path, hunk, sha256: sha256OfBytes(bytes) })
    }
    reply = kernel(['resolve', ...common, '--conflict', String(entry.i), '--reply-dir', dir,
      ...patchArgs, ...commuteArgs])
    if (reply.applied !== true) throw new Error('resolve refused: ' + JSON.stringify(reply))
    if (Array.isArray(reply.waiting)) continue   // same stop, more hunks to answer
    pending = reply.open ?? []
  }

  const out = kernel(['materialize', ...common, '--prev-head', prevHead, ...patchArgs])
  if (!out.candidateSha) throw new Error('materialize did not build a candidate: ' + JSON.stringify(out))

  return {
    candidate: out.candidateSha,
    conflictKeys: conflictKeysOf(waveDirOf(runDir, wave)),
    repliesUsed: dedupeReplies(repliesUsed),
    kernelCalls: calls,
  }
}

// ── the measurement ───────────────────────────────────────────────────────

/**
 * The set's tasks grouped by the base they were captured against: the set's own
 * BASE first, then each soft edge's recorded base in the order it first
 * appears. A set with no soft edge is one layer, and every path below collapses
 * to what it was before soft edges existed.
 */
function layersOf (spec) {
  const layers = [{ base: spec.base, tasks: [] }]
  const layerOfTask = []
  spec.tasks.forEach((task, i) => {
    const base = task.base ?? spec.base
    let at = layers.findIndex((l) => l.base === base)
    if (at < 0) at = layers.push({ base, tasks: [] }) - 1
    layers[at].tasks.push(i)
    layerOfTask[i] = at
  })
  return { layers, layerOfTask }
}

/**
 * A sampled order, reordered so no task is adopted before the layer its
 * recorded base belongs to is complete — a soft edge cannot be adopted onto a
 * head that does not yet carry what it was captured over.
 *
 * This reorders; it never drops. Every sampled order still runs, which is what
 * the constraint on the order sample asks. For a set with one layer it is the
 * identity.
 */
function stabilize (order, layerOfTask, layers) {
  const remaining = order.slice()
  const adoptedIn = layers.map(() => 0)
  const out = []
  while (remaining.length) {
    const at = remaining.findIndex((ti) => {
      for (let l = 0; l < layerOfTask[ti]; l += 1) {
        if (adoptedIn[l] !== layers[l].tasks.length) return false
      }
      return true
    })
    if (at < 0) throw new Error('no adoption order respects the recorded bases of ' + JSON.stringify(order))
    const ti = remaining.splice(at, 1)[0]
    adoptedIn[layerOfTask[ti]] += 1
    out.push(ti)
  }
  return out
}

/** `commutes` restricted to the ids in `ids`. */
const commutesFor = (commutes, ids) => Object.fromEntries(
  ids.filter((id) => commutes[id]).map((id) => [id, commutes[id]]))

/**
 * Fold one set simultaneously and in every sampled order.
 *
 *   spec.name / spec.fixture  the set's name, printed in the sim's line
 *   spec.repo             a git repo holding BASE and every patch's content
 *   spec.base             the BASE sha the set's task patches were taken
 *                         against
 *   spec.wave             the `--wave` int to fold under (default 1)
 *   spec.tasks            [{ id, patch, base? }], patch an absolute file;
 *                         `base` only for a soft edge — the head that task was
 *                         re-captured against instead of the set's BASE
 *   spec.commutes         { taskId: [path, …] }, the set's `--commutes`
 *   spec.replies          a committed reply root (see `replyFileFor`), or a
 *                         function `(ctx) => text` answering one hunk
 *   spec.replyRootAt      (ctx) => committed reply root, overriding `replies`
 *   spec.orders           orders to run, defaulting to `sampledOrders(n)`
 *   spec.workDir          scratch root; one is minted when absent
 *
 * A reply `ctx` is `{path, hunk, mode, order, ids, step, adopted}`: `mode` is
 * `'simultaneous'` or `'sequential'`, `order` the sampled order being folded
 * (null simultaneously), `ids` the task ids in adoption sequence, `step` the
 * 0-based sequential step the conflict arose at and `adopted` the ids already
 * in the head at that step.
 *
 * Returns `{ simTree, simConflictKeys, repliesUsed, orders, verdict }` —
 * `repliesUsed` being the simultaneous fold's, each order carrying its own,
 * and `verdict` `'ok'` when every order's tree is the simultaneous tree,
 * `'caught'` when one is not.
 */
export function runSet (spec) {
  const repo = spec.repo
  const wave = spec.wave ?? 1
  const tasks = spec.tasks
  const commutes = spec.commutes ?? {}
  const reply = replyResolverFor(spec)
  const work = spec.workDir ?? mkTemp('readiness-set-')
  fs.mkdirSync(work, { recursive: true })
  const orders = spec.orders ?? sampledOrders(tasks.length)
  const { layers, layerOfTask } = layersOf(spec)

  // The simultaneous fold: one fold over the whole set when it has no soft
  // edge, and otherwise one per layer — each against its own recorded base,
  // materialized onto the head the layer before it built.
  const simCtx = { mode: 'simultaneous', order: null, ids: tasks.map((t) => t.id), step: 0, adopted: [] }
  let simHead = spec.base
  const simKeys = []
  const simUsed = []
  let simCalls = 0
  layers.forEach((layer, li) => {
    if (!layer.tasks.length) return
    const layerTasks = layer.tasks.map((i) => tasks[i])
    const out = foldOnce({
      repo, base: layer.base, wave, tasks: layerTasks,
      commutes: commutesFor(commutes, layerTasks.map((t) => t.id)),
      runDir: path.join(work, 'sim', 'layer-' + li), prevHead: simHead,
      replyFor: (hunk) => reply({ ...hunk, ...simCtx }), scratch: work,
    })
    simHead = out.candidate
    simKeys.push(...out.conflictKeys)
    simUsed.push(...out.repliesUsed)
    simCalls += out.kernelCalls
  })
  const simTree = treeOf(repo, simHead)

  const results = orders.map((order, oi) => {
    const sequence = stabilize(order, layerOfTask, layers)
    const ids = sequence.map((ti) => tasks[ti].id)
    let head = spec.base
    const adopted = []
    let steps = 0
    let kernelCalls = 0
    const keys = []
    const used = []

    for (let i = 0; i < sequence.length; i += 1) {
      const task = tasks[sequence[i]]
      const soft = layerOfTask[sequence[i]] > 0
      const stepBase = soft ? layers[layerOfTask[sequence[i]]].base : spec.base
      const stepTasks = []
      const stepCommutes = {}

      if (i > 0 && !soft) {
        // The adopted frontier as one more patch against BASE — the same
        // capture the driver takes of a task's clone. A soft edge needs none:
        // the base it recorded already carries what came before it.
        const patch = path.join(work, 'adopted-o' + oi + '-s' + i + '.patch')
        fs.writeFileSync(patch, gitBytes(
          ['diff', '--binary', '--full-index', '--no-renames', spec.base, head], repo))
        stepTasks.push({ id: ADOPTED, patch })
        // and the commutes of every task already inside it: without this,
        // corpus wave 2's second step narrates `c.txt` and materialize falls
        // back, and the order disagrees with the simultaneous fold.
        const declared = []
        for (const id of adopted) for (const p of commutes[id] ?? []) if (!declared.includes(p)) declared.push(p)
        if (declared.length) stepCommutes[ADOPTED] = declared
      }

      stepTasks.push(task)
      if (commutes[task.id]) stepCommutes[task.id] = commutes[task.id]

      const stepCtx = { mode: 'sequential', order: order.slice(), ids, step: i, adopted: adopted.slice() }
      const step = foldOnce({
        repo, base: stepBase, wave, tasks: stepTasks, commutes: stepCommutes,
        runDir: path.join(work, 'o' + oi, 's' + i), prevHead: head,
        replyFor: (hunk) => reply({ ...hunk, ...stepCtx }), scratch: work,
      })
      head = step.candidate
      steps += 1
      kernelCalls += step.kernelCalls
      keys.push(...step.conflictKeys)
      used.push(...step.repliesUsed)
      adopted.push(task.id)
    }

    return {
      order: order.slice(),
      ids,
      head,
      tree: treeOf(repo, head),
      conflictKeys: dedupeKeys(keys),
      repliesUsed: dedupeReplies(used),
      steps,
      kernelCalls,
    }
  })

  return {
    name: spec.name ?? spec.fixture,
    n: tasks.length,
    simHead,
    simTree,
    simConflictKeys: dedupeKeys(simKeys),
    repliesUsed: dedupeReplies(simUsed),
    simKernelCalls: simCalls,
    orders: results,
    verdict: results.every((r) => r.tree === simTree) ? 'ok' : 'caught',
  }
}

/** M5's line for one set: the one shape the sim writes to stdout. */
export function setLine (result) {
  const first = result.orders[0]
  return [
    result.name,
    'n=' + result.n,
    'orders=' + result.orders.length,
    'tree=' + first.tree,
    'sim=' + result.simTree,
    result.verdict,
    'steps=' + first.steps,
    'kernelCalls=' + first.kernelCalls,
  ].join(' ')
}

// ── the negative control (M4) ─────────────────────────────────────────────

/** The committed reply root the control spends at 1-based step `n`. */
export const controlReplyRoot = (n) => path.join(CONTROL_REPLIES, 'step-' + n)

/**
 * The negative control: corpus wave 3's conflicting pair — `3a` rewrites the
 * region `3b` edits inside, one `lines` conflict on `d.txt` — answered from a
 * committed reply root chosen by the STEP INDEX AT WHICH `3b`, the side whose
 * edit the conflict is about, was adopted. In the order that adopts `3b` first
 * that is step 1; in the order that adopts it second, step 2. The two roots
 * hold different text, so the two orders materialize different trees.
 *
 * Keying on the step a side arrived at is precisely the mistake a real resolver
 * must not make — the task's own rule is that a reply is keyed by
 * `(set, path, hunk id)` and never by side label or step — so the control is
 * that mistake made on purpose, and `caught` is the sim noticing it.
 *
 * Why not key on the step the conflict is NARRATED at: on a two-task set it is
 * step 2 in both orders (step 1 folds a single task, which cannot conflict),
 * one reply answers both, and the orders agree however that reply is written.
 * The step a side was adopted at is the same quantity read one task earlier,
 * and it is the one that differs between the orders of a pair.
 *
 * `replyRootAt` is overridable so the same set can be built with one root at
 * every step; that copy folds to `'ok'`, which is what keeps `'caught'` from
 * being a thing the sim says unconditionally.
 */
export function negativeControlSpec (corpus, work, { replyRootAt } = {}) {
  return {
    name: 'negative-control',
    repo: corpus.repo,
    base: corpus.base,
    wave: 3,
    tasks: [
      { id: '3a', patch: corpus.patchOf(3, '3a') },
      { id: '3b', patch: corpus.patchOf(3, '3b') },
    ],
    commutes: {},
    replyRootAt: replyRootAt ?? ((ctx) => controlReplyRoot(
      ctx.mode === 'simultaneous' ? 1 : ctx.ids.indexOf('3b') + 1)),
    workDir: work,
  }
}

// ── the soft-edges pair (M7) ──────────────────────────────────────────────

/**
 * Corpus wave 2's `2b`, re-captured against the head that adopted `2a`.
 *
 * A soft edge is a task that waits for another rather than folding beside it:
 * it takes its patch against the newer head, and the fold records that head as
 * its base. `2b`'s work redone on that head is its own append merged past the
 * append already there — `git merge-file --union`, the same both-sides answer
 * the weave gives a declared-commutative path — captured from a clone at the
 * head. The pair folded that way, `2b` carrying the head as its own recorded
 * base, must land wave 2's simultaneous tree.
 */
export function softEdgesSpec (corpus, work) {
  fs.mkdirSync(work, { recursive: true })
  const repo = corpus.repo

  // The head that adopted 2a, built the way a sequential first step builds it.
  const first = foldOnce({
    repo, base: corpus.base, wave: 2,
    tasks: [{ id: '2a', patch: corpus.patchOf(2, '2a') }],
    commutes: { '2a': corpus.commutesOf(2)['2a'] ?? [] },
    runDir: path.join(work, 'adopt-2a'), prevHead: corpus.base,
    replyFor: ({ path: p, hunk }) => {
      throw new Error('adopting 2a alone narrated (' + p + ', ' + hunk + ')')
    },
    scratch: work,
  })
  const head = first.candidate

  // 2b's edit, rebased onto that head: ours = the head, base = BASE, theirs =
  // 2b's own content, unioned.
  const three = path.join(work, 'merge')
  fs.mkdirSync(three, { recursive: true })
  const ours = path.join(three, 'ours.txt')
  const ancestor = path.join(three, 'base.txt')
  const theirs = path.join(three, 'theirs.txt')
  fs.writeFileSync(ours, gitBytes(['show', head + ':c.txt'], repo))
  fs.writeFileSync(ancestor, gitBytes(['show', corpus.base + ':c.txt'], repo))
  fs.writeFileSync(theirs, contentOfTaskPatch(repo, corpus.base, corpus.patchOf(2, '2b'), 'c.txt', three))
  const merged = sh('git', ['merge-file', '--union', '-p', ours, ancestor, theirs], { buffer: true })
  if (merged.status !== 0) throw new Error('rebasing 2b onto the adopted head conflicted')

  const clone = path.join(work, 'clone-2b')
  git(['clone', '--quiet', repo, clone], repo)
  git(['checkout', '--quiet', head], clone)
  fs.writeFileSync(path.join(clone, 'c.txt'), merged.stdout)
  git(['add', '-A'], clone)
  const patch = path.join(work, 'task-2b-rebased.patch')
  fs.writeFileSync(patch, gitBytes(['diff', '--binary', '--full-index', '--no-renames', head], clone))

  return {
    name: 'soft-edges',
    repo,
    base: corpus.base,
    wave: 2,
    tasks: [
      { id: '2a', patch: corpus.patchOf(2, '2a') },
      // The soft edge: its recorded base is the head that adopted 2a.
      { id: '2b', patch, base: head },
    ],
    commutes: {},
    replies: CORPUS_REPLIES,
    workDir: path.join(work, 'set'),
  }
}

/** One path's content as a task patch leaves it — the patch applied to base. */
function contentOfTaskPatch (repo, base, patch, filePath, scratch) {
  const clone = path.join(scratch, 'apply-' + path.basename(patch))
  git(['clone', '--quiet', repo, clone], repo)
  git(['checkout', '--quiet', base], clone)
  git(['apply', '--binary', patch], clone)
  return fs.readFileSync(path.join(clone, filePath))
}

// ── the real-join sets (M6) ───────────────────────────────────────────────

/** The directories under `root` that hold a `manifest.json`, sorted by name. */
export function discoverFixtureSets (root) {
  if (!root || !fs.existsSync(root)) return []
  let entries
  try {
    entries = fs.readdirSync(root, { withFileTypes: true })
  } catch {
    return []
  }
  return entries
    .filter((e) => e.isDirectory())
    .map((e) => path.join(root, e.name))
    .filter((dir) => fs.existsSync(path.join(dir, 'manifest.json')))
    .sort()
}

/**
 * One real-join fixture directory as a `runSet` spec: its `project/` copied
 * into a scratch repo and committed is the set's BASE, its `task-<id>.patch`
 * files beside the manifest are the tasks, and `replies/` holds the committed
 * answer to anything the simultaneous fold narrates.
 */
export function fixtureSetSpec (dir, work) {
  const manifest = JSON.parse(fs.readFileSync(path.join(dir, 'manifest.json'), 'utf8'))
  const name = String(manifest.fixture || path.basename(dir))

  let project = String(manifest.project || 'project')
  project = path.isAbsolute(project) ? project : path.resolve(dir, project)
  if (!fs.existsSync(project)) project = path.resolve(REPO_ROOT, String(manifest.project))
  if (!fs.existsSync(project)) throw new Error(name + ': no project tree at ' + manifest.project)

  const repo = path.join(work, 'repo')
  fs.mkdirSync(repo, { recursive: true })
  fs.cpSync(project, repo, { recursive: true })
  fs.rmSync(path.join(repo, '.git'), { recursive: true, force: true })
  git(['init', '--quiet', '--initial-branch=main'], repo)
  git(['add', '-A'], repo)
  git(['commit', '--quiet', '-m', 'base'], repo)

  return {
    name,
    repo,
    base: git(['rev-parse', 'HEAD'], repo),
    wave: 1,
    tasks: (manifest.tasks || []).map((t) => ({
      id: String(t.id),
      patch: path.resolve(dir, String(t.patch)),
    })),
    commutes: manifest.commutes || {},
    replies: path.resolve(dir, String(manifest.replies || 'replies')),
    workDir: path.join(work, 'set'),
  }
}
