// Packs the page into the Worker: builds client/index.html and writes every
// output file into server/client-files.ts, so a deploy uploads one thing.
import {mkdtempSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {extname, join, relative} from 'node:path';

const ROOT = join(import.meta.dir, '..');
const OUT_FILE = join(ROOT, 'server', 'client-files.ts');

const TEXT_TYPES: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.txt': 'text/plain; charset=utf-8',
  '.map': 'application/json; charset=utf-8',
};

const BINARY_TYPES: Record<string, string> = {
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.wasm': 'application/wasm',
};

const walk = (dir: string): string[] =>
  readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? walk(path) : [path];
  });

const outdir = mkdtempSync(join(tmpdir(), 'tinyapp-pack-'));
try {
  const build = Bun.spawnSync(['bun', 'build', './client/index.html', '--outdir', outdir, '--minify'], {
    cwd: ROOT,
    stdout: 'inherit',
    stderr: 'inherit',
  });
  if (build.exitCode !== 0) {
    console.error('PACK FAILED: bun build exited ' + build.exitCode);
    process.exit(1);
  }

  const files: Record<string, {type: string; text?: string; base64?: string}> = {};
  for (const path of walk(outdir).sort()) {
    const key = '/' + relative(outdir, path).split('\\').join('/');
    const ext = extname(path).toLowerCase();
    const bytes = readFileSync(path);
    files[key] = ext in TEXT_TYPES
      ? {type: TEXT_TYPES[ext], text: bytes.toString('utf8')}
      : {type: BINARY_TYPES[ext] ?? 'application/octet-stream', base64: bytes.toString('base64')};
  }
  if (!files['/index.html']) {
    console.error('PACK FAILED: build wrote no index.html');
    process.exit(1);
  }

  writeFileSync(
    OUT_FILE,
    '// Generated by scripts/pack-client.ts (bun run pack). Do not edit.\n' +
      'export const FILES: Record<string, {type: string; text?: string; base64?: string}> = ' +
      JSON.stringify(files, null, 2) +
      ';\n',
  );
  console.log(`PACKED ${Object.keys(files).length} file(s) into server/client-files.ts`);
} finally {
  rmSync(outdir, {recursive: true, force: true});
}
