/** The pouf design system — the ONLY styling surface in this app.
 *
 * Screens import from here and nowhere else. No primitive accepts a className
 * or a style prop: appearance is chosen with variants, so every visual decision
 * resolves inside this folder. That is what makes the guarantee hold — change a
 * primitive (or a token in pouf.css) and the whole UI changes with it.
 */
export { Stack, Row, Spacer, Grid, Shell, Sidebar } from './layout'
export { Heading, Highlight, Eyebrow, Text } from './text'
export { Card, RowCard } from './surface'
export { Stat, Metric } from './readout'
export { Segmented } from './Segmented'
export type { SegmentedOption } from './Segmented'
export { Button, IconButton } from './Button'
export { Field, Input, Textarea } from './Input'
export { NumberInput } from './NumberInput'
export { Blob, Badge, Dot, Figure } from './media'
export { Status, Freshness, ModeBanner } from './status'
export { Empty, Skeleton, ErrorNote } from './feedback'
export { Toast, ToastViewport } from './Toast'
export type { ToastItem, ToastSeverity } from './Toast'
export { toast, dismissToast, Toaster } from './toaster'
export type { ToastVariant } from './toaster'
export { AlertBell } from './AlertBell'
export type { AlertBellItem } from './AlertBell'
export { Select, Switch, Tooltip, TooltipProvider, Confirm, Dialog, Combobox } from './controls'
export type { SelectOption } from './controls'
export { NavLink } from './NavLink'
export { BottomNav } from './BottomNav'
export type { NavItem } from './BottomNav'
export { Icon } from './Icon'
export type { IconName } from './Icon'
export { ErrorBoundary } from './ErrorBoundary'
export type { Tone } from './tone'
export { Checkbox } from './checkbox'
export { RadioGroup } from './radiogroup'
export { Slider } from './slider'
export { Tabs, Accordion, Collapsible } from './disclosure'
export { Separator } from './separator'
export { DropdownMenu, ContextMenu } from './menu'
export type { MenuEntry } from './menu'
export { Navbar } from './navbar'
export type { NavbarLink } from './navbar'
export { Footer } from './footer'
export type { FooterColumn } from './footer'
export { CTA } from './cta'
export { Menubar } from './menubar'
export type { MenubarMenu, MenubarItem } from './menubar'
export { HoverCard } from './hovercard'
export { Progress } from './progress'
export { Avatar } from './avatar'
export { Sheet } from './sheet'
export { ScrollArea } from './scrollarea'
export { AspectRatio } from './aspectratio'
export { ToggleGroup } from './toggle'
export type { ToggleOption } from './toggle'
export { Table } from './table'
export { Pagination } from './pagination'
export { Breadcrumb } from './breadcrumb'
export { AreaChart, BarChart, LineChart, PieChart } from './charts'
