#!/usr/bin/env python3
"""Convert a signed intent document into a marked plan the CURRENT engine can compile.

THROWAWAY, and deliberately NOT in `skills/ultrapowers/scripts/`: that directory
carries the ≤10 script ceiling, and spending a slot on a bridge scheduled for
deletion is exactly the accretion the ceiling guards against.

This exists for exactly one job: building the one-driver port itself
(#389/#390) on the engine that the port replaces. The new driver reads intent
documents directly and derives bodies per wave; this script is deleted at the
0.3.0 cutover along with `waves.js`.

The conversion is deliberately MECHANICAL — it invents nothing:

    intent `### T1 — title`   ->  plan `### Task 1: title`
    intent `**Depends-on:** T3, T8`  ->  plan `**Depends-on:** 3, 8`
    intent `**Files:** a, b`   ->  plan `**Files:**` block, one entry per path
    body                       ->  the intent's own Interfaces / Produces /
                                   Acceptance, verbatim

**No implementation detail is written.** That is the point, not a shortcut: it
makes the port's own build the first real test of the #243 thesis — that a task
carrying a contract and one operator-verifiable acceptance statement is enough
for an implementer, with no verbatim body. If that holds here it holds; if it
does not, we learn it on the old engine before the port depends on it.

Files: entries are typed by a rule with no judgment in it — a path that exists
in the repo is `Modify:`, one that does not is `Create:`, and anything under a
tests/ directory or named test_*/`*.test.*`/`sim_*` is `Test:`. The compiler
only distinguishes Test from non-Test for its own purposes, and a wrong guess
between Create and Modify changes nothing it computes.

Usage:  intent_to_plan.py <intent.md> [--repo <root>] [-o <plan.md>]
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

TASK_HEAD = re.compile(r"^### ([A-Z]+)(\d+)\s+—\s*(.+?)\s*$")
FIELD = re.compile(r"^-\s+\*\*([A-Za-z-]+):\*\*\s*(.*)$")
ID_REF = re.compile(r"\b([A-Z]+)(\d+)\b")


def is_test_path(p: str) -> bool:
    name = p.rsplit("/", 1)[-1]
    return (
        "/tests/" in p
        or p.startswith("tests/")
        or name.startswith(("test_", "sim_"))
        or ".test." in name
    )


def slot_text(text: str, name: str) -> str:
    """Return one slot's body. Boundaries anchor at line start: a prose mention of
    `## Cadence` in a preamble is not the heading."""
    heads = [(m.start(), m.end(), m.group(1)) for m in re.finditer(r"^## (.+)$", text, re.M)]
    for i, (start, end, n) in enumerate(heads):
        if n == name:
            stop = heads[i + 1][0] if i + 1 < len(heads) else len(text)
            return text[end:stop].strip()
    return ""


def parse_intent(text: str) -> list[dict]:
    """Split the intent's ## Tasks slot into task records. Slot boundaries anchor
    at line start — a prose mention of `## Cadence` in the preamble is not the
    heading, a trap that produced a false green the first time this was done by
    hand."""
    heads = [(m.start(), m.group(1)) for m in re.finditer(r"^## (.+)$", text, re.M)]
    slots = {name: pos for pos, name in heads}
    if "Tasks" not in slots:
        sys.exit("intent_to_plan: no '## Tasks' slot")
    after = [p for p, _ in heads if p > slots["Tasks"]]
    body = text[slots["Tasks"]: min(after) if after else len(text)]

    tasks: list[dict] = []
    for block in re.split(r"^### ", body, flags=re.M)[1:]:
        m = TASK_HEAD.match("### " + block.split("\n", 1)[0])
        if not m:
            continue
        rec: dict = {
            "prefix": m.group(1),
            "num": m.group(2),
            "title": m.group(3),
            "fields": {},
        }
        for line in block.split("\n")[1:]:
            f = FIELD.match(line)
            if f:
                rec["fields"][f.group(1)] = f.group(2).strip()
            elif rec["fields"] and line.strip():
                # continuation of the last field
                last = list(rec["fields"])[-1]
                rec["fields"][last] += " " + line.strip()
        tasks.append(rec)
    if not tasks:
        sys.exit("intent_to_plan: '## Tasks' slot has no '### <ID> — <title>' entries")
    return tasks


def render(tasks: list[dict], repo: pathlib.Path, source: str, acceptance: str) -> str:
    out: list[str] = [
        "<!-- GENERATED by intent_to_plan.py — do not edit. Source: %s" % source,
        "     Throwaway bridge for building the one-driver port on the engine it",
        "     replaces; deleted at the 0.3.0 cutover. Bodies are the intent's own",
        "     contract and acceptance statement, verbatim: no implementation",
        "     detail is authored here, by design (#243). -->",
        "",
        "# Plan — %s (generated from intent)" % source.rsplit("/", 1)[-1],
        "",
        # `**Acceptance:** suite — <rationale>`: the compiler requires the
        # em-dash rationale, and the honest one is the intent's own ## Acceptance
        # slot, condensed. Never invent a disposition the operator did not sign.
        "**Acceptance:** suite — %s" % acceptance,
        "",
    ]
    for t in tasks:
        n, f = t["num"], t["fields"]
        out.append("### Task %s: %s" % (n, t["title"]))
        out.append("")
        out.append("**Type:** implementation")
        deps = f.get("Depends-on", "").strip()
        if not deps or deps in {"—", "-", "none", "None"}:
            out.append("**Depends-on:** none")
        else:
            out.append("**Depends-on:** %s" % ", ".join(
                m.group(2) for m in ID_REF.finditer(deps)) or "none")
        if f.get("tier"):
            out.append("")
            out.append("_tier: %s (signed)_" % f["tier"])
        out.append("")
        out.append("**Files:**")
        for path in re.findall(r"`([^`]+)`", f.get("Files", "")):
            if is_test_path(path):
                label = "Test"
            else:
                label = "Modify" if (repo / path.rstrip("/")).exists() else "Create"
            out.append("- %s: `%s`" % (label, path))
        out.append("")
        if f.get("Interfaces"):
            out.append("**Interfaces:** %s" % f["Interfaces"])
            out.append("")
        if f.get("Produces"):
            out.append("**Produces:** %s" % f["Produces"])
            out.append("")
        out.append("**Acceptance (signed — the operator verifies exactly this):** %s"
                   % f.get("Acceptance", "MISSING"))
        out.append("")
    return "\n".join(out)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("intent")
    ap.add_argument("--repo", default=".")
    ap.add_argument("-o", "--out")
    a = ap.parse_args()
    src = pathlib.Path(a.intent)
    tasks = parse_intent(src.read_text())
    acc = " ".join(slot_text(src.read_text(), "Acceptance").split())
    if not acc:
        sys.exit("intent_to_plan: intent has no '## Acceptance' slot to carry over")
    text = render(tasks, pathlib.Path(a.repo), a.intent, acc)
    if a.out:
        pathlib.Path(a.out).write_text(text)
        print("wrote %s (%d tasks)" % (a.out, len(tasks)))
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
